### ISSUE TITLE
Provide more complex examples to shorten learning time

### ISSUE THREAD

**Issue by junakowicz** [timjroberts/cucumber-js-tsflow#1]
Hi,

Can you please provide some examples more complex ones if possible as well.

This will be very helpful and should speed up first steps.

Thanks

**Comment by timjroberts** [comment]
Thanks @junakowicz. I'll look at providing some more concrete examples as soon as I can. Hopefully though, anyone who has used SpecFlow in C#/.NET will pick it up because I've tried to model a lot of the features from there, and the project is intentionally a very thin veneer around CucumberJS.

**Comment by BibbyChung** [comment]
I need it too. I don't know how to start to use it quickly. Please.... ^^

**Comment by timjroberts** [comment]
I've updated the README.md file to contain a 'Quick Start' section that should help folks get going. Let me know if it has been of use.

**Comment by BibbyChung** [comment]
Thanks....

**Comment by samvloeberghs** [comment]
Some more examples [here](https://github.com/samvloeberghs/protractor-gherkin-cucumberjs-angular2/tree/master/test/e2e/authentication)
