### ISSUE TITLE
Project abandoned?

### ISSUE THREAD

**Issue by Fryuni** [timjroberts/cucumber-js-tsflow#105]
There hasn't been any commit to this project for over a year, and community PRs have also seen no movement.
Some issues (eg #45) have been merged but not added to the v4 releases, meaning that there are a bunch of already fixed problems that continue to affect anyone using recent cucumber versions.

What is the current status of this project? If it is looking for maintainers, we might be able to help. If there is no desire to continue this project, we will fork it for internal use.

**Comment by timjroberts** [comment]
I don't use the project (or CucumberJS) these days, so the project has fallen through the cracks. A few others have helped contribute to the maintenance over the years, and I'm more than happy to give maintainer access to others that want to continue it.

**Comment by Fryuni** [comment]
Hey @timjroberts, thanks for the quick reply. I use this project a lot at work and on personal projects, so I'd like to volunteer as a maintainer.
I noticed that there are other maintainers as well; if any of you would like to talk first, you can ping me here or send me an email :)

**Comment by mikehaas763** [comment]
@Fryuniet I’m not currently using this project, but I’m happy to try to answer questions if you have any.

**Comment by Fryuni** [comment]
@mikehaas763 I don't have any immediate question actually, the issues that I fixed locally were quite easy to fix and/or were already fixed on v3.

What I'd do first is port those to the v4 branch and get those update PRs sorted out. Then this project will be part of my OSS list so I gradually work on the issues. I really like the project :)

If there are some maintainers just to review my PRs I can port the fixes on a fork.

**Comment by timjroberts** [comment]
I've invited you to become a Collaborator @Fryuni - watch for the email :-)

The project started out as an experiment with TypeScript Decorators and a little _glue_ code to make the bindings into CucumberJS work. I'm surprised by how used the package is. Given its simplicity, there aren't that many moving parts in it, and most of the changes are down to underlying changes in the API surface of CucumberJS itself.

Since TypeScript and CucumberJS have both changed quite a bit since I started this project, and some elements are no longer idiomatic, perhaps the time is right for a rewrite.

**Comment by Fryuni** [comment]
> I've invited you to become a Collaborator

Thanks, I'll start fixing things on v4 this week.

> I'm surprised by how used the package is.

It is simple but not trivial, solves a painful problem (cucumber state management), and is very practical. The perfect recipe for a package.

> Since TypeScript and CucumberJS have both changed quite a bit since I started this project, and some elements are no longer idiomatic, perhaps the time is right for a rewrite.

I might look into that in the mid-term future.
