### ISSUE TITLE
this._worldObj undefined in before/after hook

### ISSUE THREAD

**Issue by reece-white** [timjroberts/cucumber-js-tsflow#113]
The world obj is undefined in the before/after hooks so it is unable to attach a screenshot.

Example fix: https://github.com/timjroberts/cucumber-js-tsflow/pull/112

**Comment by Fryuni** [comment]
The world object is not exposed intentionally. It might be available during a step function, but it is not guaranteed (it probably won't be exposed for long).

The World object has four uses:
- Receiving the value from the `world-parameters` cucumber option
- Attaching logs to a specific step in cucumber
- Attaching files to a specific step in cucumber
- Sharing data between steps

Sharing data is supported with [context injection](https://github.com/timjroberts/cucumber-js-tsflow#context-injection). If you want your data to be shared between all your steps you can use the same context type for all your bindings:
https://github.com/timjroberts/cucumber-js-tsflow/blob/818aa9edcac244e058d1a12c0a918c4039a9f2e8/cucumber-tsflow-specs/features/custom-context-objects.feature#L18-L53

The three other functionalities of the World object are exposed through the three [provided context types](https://github.com/timjroberts/cucumber-js-tsflow#provided-context-types).

To attach a screenshot you can use the `CucumberAttachments` like shown here:
https://github.com/timjroberts/cucumber-js-tsflow/blob/818aa9edcac244e058d1a12c0a918c4039a9f2e8/cucumber-tsflow-specs/features/provided-context-objects.feature#L46-L61

**Comment by Fryuni** [comment]
To be sure, and to prevent future regressions, I just added an extra scenario testing attachments on both `before` and `after` hooks here: https://github.com/timjroberts/cucumber-js-tsflow/commit/979a0c8600ff4bfb5a37a3e3e109c4f01769fd70
