### ISSUE TITLE
Context Injection with async functions (promise)

### ISSUE THREAD

**Issue by ericrommel** [timjroberts/cucumber-js-tsflow#114]
Hi,

I'm using cucumber-js with ts-flow and I'm facing an issue. I have split the feature and step definitions folders and files for better understanding (there are more than 50 features in my system). I'm using Context Injection to share the data between the files but I'm having an issue sharing Promise objects between them. The objects are undefined (objects only get the value at the end of the execution.
I will try to write here what I have.

```typescript
// login.helper.ts
export class Login {
  public configuration: any
  public accountApi: AccountApi
  
  public axios: any = axiosFactory({
     // set some configs here
  })

  public blabla() {
   // It is using the axios config
    return new Promise(function(resolve, reject) {
      setTimeout(() => resolve("New value from LogIn()"), 1000)
    })
  }
  public async LogIn() {
   // There is an api call (using Axios) here to set some configs. Used blabla() just as an example
    this.configuration = await this.blabla()
  }

  public async setAccountApi() {
    this.accountApi = new AccountApi(this.configuration) // there is 
  }
}
```

```typescript
// account.step.ts
import { binding, then, when } from 'cucumber-tsflow'
import { assert } from 'chai'
import { Login } from '../../helpers/login.helper

@binding([Login])
export class AccountSteps {
  private bankAccountsInfo: Any
  constructor(protected login: Login) {
     this.login.LogIn()
   }
 
  @when('Do something with this id {string}')
   public async requestAccountInfo(id: number) {
     // This should use this.configuration set after the constructor execution and will set the accountApi, but this.configuration is undefined here.
     this.login.setAccountApi()
     this.bankAccountInfo = await this.login.accountApi.getBankAccounts(id)
     // As this.configuration is undefined previously, this.accountApi will not be filled, and there is no `.getBankAccounts`
   }

  @then('I see something')
   public async thenCheckBankAccountInfo() {
     const bankAccount = this.bankAccountInfo.data.clientBankAccounts
     assert.isAtLeast(bankAccount.length, 1)
   }
}
```

The sample example from documentation works fine but this example is not using async/promise.
Is there any issue/limitation to use it? Is there any example using promise that I could check?
I hope it was clear enough. Let me know if not.

Thanks...

**Comment by Fryuni** [comment]
From your code`
> This should use this.configuration set after the constructor execution

Your example is not calling `this.login.LogIn()` anywhere, so `this.configuration` inside the `Login` class is never set.

If you add a constructor for the `Login` class doing that then it should work as you described:
```ts
export class Login {
  public configuration: any
  public accountApi: AccountApi

  // Notice that constructors for context classes cannot receive any arguments for now
  public constructor() {
    this.LogIn();
  }

  ...
}
```

**Comment by ericrommel** [comment]
Hi @Fryuni,

Thank you for your help. Actually, I forgot to write this part, however, I'm calling the `this.login.LogIn()` inside the `account.step.ts` file. I have updated the code there. Is it okay?

**Comment by timjroberts** [comment]
I wonder if your issue is because you're calling `this.login.Login()` from the constructor of the step. `Login()` is an async function, but you can't have async constructors. I think the step is then racing ahead because the async `Login()` is now being awaited (hence you see `undefined` for your values).

Try moving the call to `this.login.Login()` into the 'when' step (before you call `this.login.setAccountApi()`) so see if that works and that you no longer see`undefined` values. If so, then you can refactor the code to use a before hook if you really want to login before your 'when' steps execute.

**Comment by ericrommel** [comment]
Hey @timjroberts, worked as a charm. Thank you so much. It is now into a hook file and working fine.
