### ISSUE TITLE
beforeAll and afterAll undocumented despite being usable

### ISSUE THREAD

**Issue by max-carroll-sky** [timjroberts/cucumber-js-tsflow#120]
in the cucumber js docs we have beforeAll and afterAll, these are present in your APIs but are not documented on your page

Perhaps a little snippet with an example would help, something like this

```
import { beforeAll } from 'cucumber-tsflow';

 @beforeAll()
    public async beforeRunningTheWholeSuite() {
        ...
    }
```

**Comment by max-carroll-sky** [comment]
I would be happy to create a PR for this if you guys need any help and you agree

**Comment by Fryuni** [comment]
Added to the README and added missing tests on this commit: e783156b58509e122e9a47641e6101f216c750fc
