### ISSUE TITLE
Support for named hooks

### ISSUE THREAD

**Issue by nnaynnay** [timjroberts/cucumber-js-tsflow#129]
Hello, would like to know if any plan to support [named hooks which was added in cucumber-js v8.1.0](https://github.com/cucumber/cucumber-js/blob/v8.1.0/docs/support_files/hooks.md#named-hooks) ? 
To allow something like this:
```ts
@before({ name: 'scenario name' })
```

**Comment by Fryuni** [comment]
I didn't know about that feature, very lovely. The current version of this library still supports cucumber 7, so this would either be a breaking change, or I need to ensure at the type level that the `name` property would not be accepted when running with cucumber without that feature.

It seems relatively easy, but if not, this would be only for v5. I want to simplify many things, especially the development workflow for v5, so it is quite far on the horizon.

Let me try it out to see if I can make it happen, in which case I might even include it in the release I'll make today.

**Comment by Fryuni** [comment]
Yeah, it is quite simple, opening a PR for it right now 😄

Thanks for the idea!

**Comment by Fryuni** [comment]
Will be in the next release

**Comment by Fryuni** [comment]
It is already out v4.1.1
