### ISSUE TITLE
typo on demo homepage

### ISSUE THREAD

**Issue by huineng** [timjroberts/cucumber-js-tsflow#15]
class ArithmeticSteps {
    private computedResult: number;

    @given(/I enter '(\d*)' and '(\d*)'"/)

should be  @given(/I enter '(\d*)' and '(\d*)'/)  (no " at the end)

**Comment by stupiduglyfool** [comment]
I created a pull request which includes this fix https://github.com/timjroberts/cucumber-js-tsflow/pull/19
