### ISSUE TITLE
@then(/number \$(\d*)/) does not call function with number parameter

### ISSUE THREAD

**Issue by AnselmHa** [timjroberts/cucumber-js-tsflow#154]
Great job, by the way.
I refer to this blog post: https://www.elliotdenolf.com/blog/cucumberjs-with-typescript

The issue is, when I try to use cucumber-js-tsflow together with playwright, equal check does not work anymore, as playwright toEqual checks type as well.
`

import { assert } from 'chai';
import { expect } from "@playwright/test";

  @then(/The bank account balance should be \$(\d*)/)
  public accountBalanceShouldEqual(expectedAmount: number) {
    console.log(typeof expectedAmount); // string
    console.log(typeof this.accountBalance); //number
    assert.equal(this.accountBalance, expectedAmount); //success
    expect(this.accountBalance).toEqual(expectedAmount); //fails
  }
`

Is there a possibility to add number type for "\d"- Regex in e.g. "@then"?

**Comment by Fryuni** [comment]
The processing of those parameters in the step string is done by the `@cucumber/cucumber` itself, not by the `cucumber-taflow` wrapper.

I think all regex will be passed as string regardless of pattern.

You can use the template strings, which are more restricted but include casting:
```
@then("The bank account balance should be ${number}")
```

**Comment by Fryuni** [comment]
The processing of those parameters in the step string is done by the `@cucumber/cucumber` itself, not by the `cucumber-taflow` wrapper.

I think all regex will be passed as string regardless of pattern.

You can use the template strings, which are more restricted but include casting:
```
@then("The bank account balance should be ${number}")
```
