### ISSUE TITLE
Support for World Parameters

### ISSUE THREAD

**Issue by dsole** [timjroberts/cucumber-js-tsflow#16]
I'm assuming the intention is that the Workspace injection into a bound class replaces the World class that is normally used in cucumberJS.  Are [World Parameters](https://github.com/cucumber/cucumber-js/blob/master/docs/cli.md#world-parameters) supported ?   Or is there another way to get CLI parameters into a Workspace ?

For example when I run cucumberJS I'd like to pass the base URL of the web application that the tests should run against. And then in the Workspace, a selenium driver is created that opens that URL.
Example:
```
node node_modules/cucumber/bin/cucumber.js --world-parameters '{"url": "http://my.testsite.com/"}'
```
and then the workspace
```
class SeleniumWorkspace {
  constructor(config) {
    this.url = config.url || defaultUrl;
  }
  public url: string;
}

```

I was hoping that the world parameters would come through into the Workspace constructors (as they do with a World class) but that doesn't seem to be the case.

If you think that would be a good feature I'm happy to code it up and submit a PR

**Comment by timjroberts** [comment]
You're correct in that the Context Injection is aimed at replacing the World (so that it models SpecFlow a little more). Being able to access the World Parameters does sound like a useful feature though. I'm happy to accept PRs.

You could probably abstract and hide an internal World and then expose it somehow (either as ambient context [i.e., `WorldContext.current["url"]`], or have a World context object available that is actually injectable).

**Comment by AlexandrosD** [comment]
A workaround using protractor is use the `browser.params` object instead of World, and store there whatever needs to be shared between different step definitions, handlers, etc.

**Comment by jthomerson** [comment]
@wudong @mikehaas763 I'm not sure why this one was closed, but is there a chance this could be addressed? Or if there's a way to do it already, can you point me in that direction?

Related: #40

**Comment by jthomerson** [comment]
Sorry to follow up on my own question, but in case someone else comes, I based this off #40:

If you have some world parameter `fileRoot`, i.e. `./node_modules/.bin/cucumber-js --world-parameters '{"fileRoot":"some/path/to/files"}`

Then you can access it in your steps like this:

`const fileRoot: string = (this as any)._worldObj?.parameters?.fileRoot;`
