### ISSUE TITLE
WebPack error

### ISSUE THREAD

**Issue by connelhooley** [timjroberts/cucumber-js-tsflow#17]
I'm trying to use Cucumber JS with the Angular CLI. By default the CLI uses Jasmine and Karma. I've installed a Cucumber JS plugin for Karma. The CLI is compiling my project using Webpack.

I'm getting the following warnings then an error when I import the package (even without using it):

> WARNING in ./~/cucumber-tsflow/index.js
> 3:24 Critical dependency: require function is used in a way in which dependencies cannot be statically extracted
Chrome 54.0.2840 (Windows 10 0.0.0) ERROR

I've googled it and it appears to be a Webpack warning although I'm not entirely sure what it means!

**Comment by mikehaas763** [comment]
I don't think this happens anymore with the new build
