### ISSUE TITLE
DataTable example

### ISSUE THREAD

**Issue by YvdV** [timjroberts/cucumber-js-tsflow#18]
I am trying to use step with data table but cannot get data in step.
Feature file contains following step:

Then  the list of institutes contains
      | I1 |
      | I2 |
      | I3 |
      | I4 |

Step file:

  @then(/^the list of institutes contains$/)
  thenTheListOfInstitutesContains(institutes: TableDefinition, callback: CallbackStepDefinition){
    this.patientSearchPage.getInstitutes().then(actualInstitutes => {
      console.log(actualInstitutes.length);
      console.log(institutes.rows.length);
      expect(actualInstitutes.length).to.equal(institutes.rows.length);
      callback();
    });   
  }

institutes.rows.length = 0, where I would expect it to be 4. I tried using DataTable instead of TableDefinition, but DataTable is not recognized as a type and I do not know where to import it from. Also changing the order of the arguments (institutes as second) did not have any effect.

Anyone has a working example for table using tsflow?

**Comment by YvdV** [comment]
After a lot of console.logs I finally managed to get it working.

1. I changed type of institutes from TableDefinition to any.
2. And rows is not a property of DataTable, but a function, so it should be rows().length.
3. And I had to include a header row in the feature file, otherwise I only got three rows instead of four.

For anyone interested, the end result:
feature file:
`    Then  the list of institutes contains
      | code |
      | I1   |
      | I2   |
      | I3   |
      | I4   |`

steps file:
  @then(/^the list of institutes contains$/)
  thenTheListOfInstitutesContains(institutes: any, callback: CallbackStepDefinition){
    this.patientSearchPage.getInstitutes().then(actualInstitutes => {
      expect(actualInstitutes.length).to.equal(institutes.rows().length);
      for(let row of institutes.rows()){
         expect(actualInstitutes.some(i => i === row[0])).to.be.true;
      }
      callback();
    });   
  }
}

**Comment by samvloeberghs** [comment]
I think you're getting the basics of scenario outlines wrong.
You should implement a datatable as given here:
https://github.com/samvloeberghs/protractor-gherkin-cucumberjs-angular2/blob/master/test/e2e/authentication/login/login.feature

```feature
Feature: This feature describe the scenarios of the login part of our authentication component

  Scenario Outline: The user is using the login form

    Given user clicks the login link
    And '<email>' is the user email in the login form
    And '<password>' is the user password in the login form
    When submitting the login form
    Then the login form is validated '<valid>'

    Examples:
      | email         | password             | valid |
      |               |                      | false |
      |               | thisisavalidpassword | false |
      | samkwerri.be  | thisisavalidpassword | false |
      | sam@kwerri.be |                      | false |
      | sam@kwerri.be | thisisavalidpassword | true  |
```
