### ISSUE TITLE
Cucumber couldn't find your step definitions

### ISSUE THREAD

**Issue by provnataliya** [timjroberts/cucumber-js-tsflow#20]
My team wants to start creating e2e automated tests for our application using Cucumber and Typescript. We found your example on https://github.com/timjroberts/cucumber-js-tsflow. 
We tried to get it working, but wasn’t able.
We would greatly appreciate your help.
Here is what I have done, according to your description:
1)	Created a new project folder
2)	Download Node Js  and install locally
3)	npm install cucumber cucumber-tsflow
4)	npm install typescript@next
5)	Created “ feature” folder and saved file my_feature.feature:
-----
Feature: Example Feature
   This is an example feature

   Scenario: Adding two numbers
      Given I enter '2' and '8'
      Then I receive the result '10'
---------
6)	Created /ArithmeticSteps.ts file:
--------
// features/ArithmeticSteps.ts
import { binding, given, then } from "cucumber-tsflow";
@binding()
class ArithmeticSteps {
    private computedResult: number;

    @given(/I enter '(\d*)' and '(\d*)'"/)
    public givenTwoNumbers(num1: string, num2: string): void {
        this.computedResult = parseInt(num1) + parseInt(num2);
    }

    @then(/I receive the result '(\d*)'/)
    public thenResultReceived(expectedResult: string): void {
        if (parseInt(expectedResult) !== this.computedResult) {
            throw new Error("Arithmetic Error");
        }
 }
}

export = ArithmeticSteps;
-------------------------------

7. Created tsconfig.json file with "moduleResolution": "node":
8. Project directory structure looks like this:
![projectstructure](https://cloud.githubusercontent.com/assets/11686689/22562140/2d0d67ca-e930-11e6-8adf-f717d759b3c4.JPG)
 
9. After I compiled this with tsc, I got .js file in a root directory: 
 
![projectstructureaftercompiling](https://cloud.githubusercontent.com/assets/11686689/22562149/386617f2-e930-11e6-949c-4ef9c4b53e29.JPG)

10. When I run Cucumber (C:\CucumberTS>node_modules\.bin\cucumber.js.cmd), I am getting an error:   
“Undefined. Implement with the following snippet:
       Given('I enter \'{arg1:int}\' and \'{arg2:int}\'', function (arg1, arg2, callback) {
         // Write code here that turns the phrase above into concrete actions
         callback(null, 'pending');
       });)

![errors](https://cloud.githubusercontent.com/assets/11686689/22562179/51884aca-e930-11e6-8730-a20f43747ee9.JPG)

**Looks like Cucumber couldn't find step definitions.**

11. Using C:\CucumberTS>node_modules\.bin\cucumber.js.cmd ArithmeticSteps.js didn't help, I got another error:
![errror_windowisnot defined](https://cloud.githubusercontent.com/assets/11686689/22562483/972ed2fa-e931-11e6-9401-21c8d711ca8a.JPG)

12.Using C:\CucumberTS>node_modules\.bin\cucumber.js.cmd -r C:\CucumberTS\ gave the same error:
![windowisnotdefined2](https://cloud.githubusercontent.com/assets/11686689/22562548/dd0862e6-e931-11e6-9e86-331951ff3e9d.JPG)

 
Please, help!!! How should I run this correctly to get it working? Thank you very much in advance!

**Comment by ChrisMancini** [comment]
Is it possible that you are using cucumber-2.0.0-rc0 or greater?

If that is the case, it seems the manner in which steps are defined has changed.

See:  https://github.com/cucumber/cucumber-js/blob/v2.0.0-rc.0/CHANGELOG.md

> String patterns were removed in favor cucumber-expressions

Here is the documentation for cucumer-expressions:  https://docs.cucumber.io/cucumber-expressions/

I think this package is not currently compatible with cucumber 2.0.

**Comment by orieken** [comment]
I was able to get this working using 
ts-node: 1.6.1 
typescript: 2.0.6
protractor: 5.1.1
cucumber: 1.3.1 
cucumber-tsflow: 1.1.2 
https://github.com/orieken/cucumber-tsflow-example
<img width="788" alt="screen shot 2017-02-23 at 6 08 38 pm" src="https://cloud.githubusercontent.com/assets/626030/23283301/234f4aae-f9f3-11e6-8e11-34ff6e65062c.png">

**Comment by davladus** [comment]
Example from cucumber-tsflow-specs doesn't work for me either. 
tried

        "cucumber-tsflow": "1.1.2",
        "cucumber": "1.3.1"
```
.\node_modules\.bin\cucumber-js.cmd
```

```
1) Scenario: Test Scenario - features\test.feature:4
   Step: Given foo - features\test.feature:5
   Message:
     Undefined. Implement with the following snippet:

       this.Given(/^foo$/, function (callback) {
         // Write code here that turns the phrase above into concrete actions
         callback(null, 'pending');
       });

1 scenario (1 undefined)
1 step (1 undefined)
0m00.000s

```

**Comment by bastiannijboer** [comment]
I tried the same. Doesn't work for me either

**Comment by bastiannijboer** [comment]
I had the same problem, but got it to work now. What helped me is to use the generated steps by cucumber instead of the step definition file given in the example.

**Comment by timjroberts** [comment]
I've released version 2.2.0 which works with CucumberJS 2.2.

**Comment by prasannarhegde2015** [comment]
I still have same issue with latest cucumber and protractor
none of workaround seem to work for me

Also help me to get version of cucumber what is the command on windows( windows 10 to be precise)

Strange thing is that what was working fine few days back started giving this issue 
Suddenly cucumber cant find step definitions

**Comment by hsnsalhi** [comment]
+1

**Comment by abdulazizkarim11** [comment]
I have encountered this issue of cucumber ignoring my scripts. It turns out there's been a lot of changes since cucumber released its versions. I recommend you upgrading cucumber and using the step definitions output for your steps. Also, check your package file and ensure you have the following set up
"test": "cucumber-js"

This way you can use "npm test" to run your tests.
