### ISSUE TITLE
Property 'decorate' does not exist on type 'typeof Reflect'. (2339)

### ISSUE THREAD

**Issue by neekers** [timjroberts/cucumber-js-tsflow#21]
Trying to set this whole thing up using Angular-CLI and protractor and cucumber and TypeScript.

I have my steps file there and it seems to be looking at it, but now I get this error

```
Property 'decorate' does not exist on type 'typeof Reflect'. (2339)
```

It's a very simple test. I get the error 3 times. Seems to correlate with the method decorators

protractor-cucumber-framework@1.0.1
protractor@5.1.1
@angular@2.4.9
ts-node@2.1.0
cucumber@1.3.1
typescript@2.0.10

**Comment by gnesher** [comment]
Seeing the same problem

**Comment by harshabonthu** [comment]
@neekers I'm getting the same error with Angular cli. Were you able to find any solution / work around? Thanks.

**Comment by jonathanburrows** [comment]
@harshabonthu I was getting the same error. Was working for _ng build_, but not _ng e2e_. I believe protractor does not include the polyfill correctly. Was able to work around by adding _import 'reflect-metadata';_ to each file that had a reference to _Reflect_.

**Comment by vitalics** [comment]
@neekers probably typescript cannot be found `Reflect` namespace. Try install `reflect-metadata` library. Just write `npm i -S reflect-metadata` and try again

**Comment by iliyaZelenko** [comment]
I was helped by the installation package for babel: `@babel/preset-typescript`.

**Comment by Taewa** [comment]
Hi @iliyaZelenko 
Could you tell me how you applied babel with cucumber-ts-flow?
