### ISSUE TITLE
Is it compatible with cucummber 2

### ISSUE THREAD

**Issue by fredgate** [timjroberts/cucumber-js-tsflow#22]
I am using cucumber 2.0.0 RC7 and the steps that I define using @binding, @given, @when, @then are not retrieved by cucumber.

Here is my very simple code :
```
import {binding, given, then} from 'cucumber-tsflow';

@binding()
class AddTodoSteps {

    @given(/I have an existing list/)
    public givenExistingList() {
    }
}

export = AddTodoSteps;
```

My Given step is not retrieved by cucumber.

If I write pure javascript like below :
```
var {defineSupportCode} = require('cucumber');

defineSupportCode(function({Given, When, Then}) {

    Given('I have an existing list', function (callback) {
        // Write code here that turns the phrase above into concrete actions
        callback(null, 'pending');
    });
});
```
The Given step is found by cucumber.
Note the _defineSupportCode_ present in cucumber 2 since RC4.

**Comment by sSeewald** [comment]
No, it's not compatible. You need to use cucumberjs 1.3.1

**Comment by AlexandrosD** [comment]
Is there a clear understanding of what is needed to support cucumber 2.0?

**Comment by marcusvetter** [comment]
Not for me. Does anyone know what we have to do to support cucumber 2.0?

**Comment by KeithGillette** [comment]
The [CHANGELOG for Cucumber.JS](https://github.com/cucumber/cucumber-js/blob/master/CHANGELOG.md) purports to outline the breaking changes in 2.0.0.

The change of most relevance to `cucumber-js-tsflow` appears to me to be in [2.0.0-rc.4](https://github.com/cucumber/cucumber-js/blob/master/CHANGELOG.md#200-rc4-2016-12-19), which changed from exporting the function and calling methods on `this` to instead passing the function to `defineSupportCode` and receiving cucumber methods as injected arguments.

**Comment by tamascsaba** [comment]
hi, @timjroberts have you got any plan to make cucumber-js-tsflow compatible with cucumber 2.x?

**Comment by timjroberts** [comment]
@tamascsaba I've started to look at code this evening, and I have it working with CucumberJS 2.2. I need to look at integrating the step binding snippet building which has also changed in the 2.2 API surface, but I'm hopeful I can make that work too.

I'll hopefully have a `2.2.0-alpha` release this weekend (_I'll also align the version numbers with CucumberJS so it becomes more obvious as to which minimum version of CucumberJS will be required_).

**Comment by tamascsaba** [comment]
@timjroberts nice job, thx 👍

**Comment by timjroberts** [comment]
`2.2.0` has just been pushed to npm.
