### ISSUE TITLE
No "and" keyword ?!

### ISSUE THREAD

**Issue by mica16** [timjroberts/cucumber-js-tsflow#27]
Hi, 

I'm using cucumber-tsflow and I've just noticed that it lacks the  step keyword: "and". 

My Gherkin scenario has this workflow:

Given
And
When
Then

Why does it lack it?         
How to manage it? 

Thanks a lot!

**Comment by timjroberts** [comment]
With 'And' it implies that you're still in the previous type of step. So in your example, you would write the step definition as if it were a 'Given':

```typescript
@given(/.../)
public givenSomething(): void {
  ...
}
```

**Comment by mica16** [comment]
That's exactly what I've done, thanks ;) 
But it would be less akward to handle the "and" keyword by the way.

**Comment by timjroberts** [comment]
Unfortunately it's part of CucumberJS. All other Cucumber and Gherkin implementations would work the same way. All cucumber-tsflow does it wrap CucumberJS with decorators so that you can write step definitions using classes.
