### ISSUE TITLE
Support for `setDefaultTimeout`?

### ISSUE THREAD

**Issue by KeithGillette** [timjroberts/cucumber-js-tsflow#29]
Thanks for this very useful package, which we've found invaluable in implementing readable and maintainable CucumberJS tests.

Does `cucumber-js-tsflow` support global configuration of the timeout on asynchronous hooks and steps as with [CucumberJS `setDefaultTimeout`](https://github.com/cucumber/cucumber-js/blob/master/docs/support_files/timeouts.md) or is the timeout only configurable on each step?

**Comment by timjroberts** [comment]
Currently it's only supported at each step if you go through cucumber-js-tsflow. However, all the decorators simply wrap around the CucumberJS library, so you should be able to mix calls to CucumberJS with the bindings that cucumber-js-tsflow provide. Putting the following lines into one of your files should do the same thing:

```javascript
var {defineSupportCode} = require('cucumber');

defineSupportCode(function({setDefaultTimeout}) {
  setDefaultTimeout(60 * 1000);
});
```

**Comment by KeithGillette** [comment]
Thanks for the fast and helpful, reply, @timjroberts. Is there a recommended way to configure Cucumber under `cucumber-js-tsflow` to execute such setup calls before executing feature tests?

**Comment by folterung** [comment]
If there is a recommended way for configuration I would like to know as well. I currently have a project with `protractor + typescript + cucumber-js-tsflow` and I cannot figure out how to override the default timeout so everything times outs after 5000 milliseconds. Any insight would be appreciated.

@timjroberts @KeithGillette

**Comment by ronlawrence3** [comment]
Hey @folterung did you do anything else but create this file and reference it  in the protractor.conf.js in cucumberOpts.require? I'm not having any luck with that in a similar project.

**Comment by OhadR** [comment]
Hi,

> Currently it's only supported at each step if you go through cucumber-js-tsflow

maybe I miss something, but if this (great) package supports timeouts in a step level, how can I set it? The code above, as far as I understand, sets the timeout for ALL steps. But in my case, I have a single step which take a lot of time so I want to allow specifically this step to run 5 minutes (and not other steps).

How can I achieve that? 

here is the code that I use to set the "global" timeout, meaning the timeout for ALL steps:

```
var {setDefaultTimeout} = require('cucumber');
setDefaultTimeout(10 * 1000); 
```
