### ISSUE TITLE
DeprecationWarning: cucumber: defineSupportCode is deprecated

### ISSUE THREAD

**Issue by vitalics** [timjroberts/cucumber-js-tsflow#31]
**Workspace**:

| name            	|          verion         	|
|-----------------	|:-----------------------:	|
| cucumber        	|          4.2.1          	|
| cucumber-tsflow 	|          2.2.0          	|
| typescript      	|          2.8.1          	|
| ts-node         	|          6.0.0          	|
| nodejs          	|          8.9.4          	|
| npm             	|          5.6.0          	|
| OS              	| Windows 10 version 1703 	|

![image](https://user-images.githubusercontent.com/8816260/38995926-b1aae0fc-43f2-11e8-9a4e-3f104f106619.png)

However, if remove `binding()` decorator - all tests is fail (see next screen)

![image](https://user-images.githubusercontent.com/8816260/38996077-0ef8d642-43f3-11e8-9ddc-102adff3bfa9.png)

**Comment by mikehaas763** [comment]
Closed by https://github.com/timjroberts/cucumber-js-tsflow/commit/31c2bdb854712ec03b733eeb57492fe0954d2789
