### ISSUE TITLE
VSCode (1.31.1) debugging doesn't work properly

### ISSUE THREAD

**Issue by adamlubek** [timjroberts/cucumber-js-tsflow#38]
Hi,
TypeScript debugging in visual studio code (using VSC debugger) doesn't work properly anymore. When I set breakpoints in cucumber related TS code, break point is hit but code isn't highlighted, code context on hover isn't available etc. 
Everything starts working though, when I click on paused break point in any of call stack entries in VSC debugger's call stack explorer. 
VSC debugging is working fine when debugging other configurations (e.g. angular app or unit tests), it's TypeScript files associated with cucumber tests that don't work. I also checked previous VSC code version (1.30.2) and everything works fine.

VSC about:
![untitled](https://user-images.githubusercontent.com/8349742/53413365-ac156500-39c3-11e9-9f66-ef098153d9bd.png)

**Comment by kferrone** [comment]
That's more of an issue with Decorators and Typescript. Ive seen the same issue with other similar projects. In the case of cucumber, the files are loaded implicitly through `--require-module` which then implicitly `--requires` files. I'm thinking this issue is not the fault of `cucumber-ts-flow`.

**Comment by wudong** [comment]
Added a brief guide to debug in IDEs
