### ISSUE TITLE
Access world object (this)

### ISSUE THREAD

**Issue by okkes** [timjroberts/cucumber-js-tsflow#40]
Is there any way to access/inject the world object to the step definitions?

In order to attach a screenshot to cucumber-html-reporter, I need to call this.attach() method, but that won't work in typescript as the attach method doesn't exist.

**Comment by ed4becky** [comment]
OK figured it out, sharing my strategy.

1 create a context object to replace the world.  this gets injected into the step definition object

```
export class SeleniumWorld {
  driver: WebDriver;
  waitForElement: any;

   constructor () {
    this.init();
  }

  init () {
    // Returns a promise that resolves to the element
     this.waitForElement = async function (locator: any) {
      const condition = SeleniumWebdriver.until.elementLocated (By.css(locator));
      return await this.driver.wait (condition);
    };
  }
}
```


My first mistake was trying to initialize the driver in the object - now I just have a reference to it.

2. make sure to inject the context

```
@binding([SeleniumWorld])
class IdentifySourceStepDefinitions {

  w: SeleniumWorld;
  base: BasePage;
  page: IdentifySourcePage;

  constructor (protected world: SeleniumWorld) {
    this.w = world;
    this.base = new BasePage(this.w);
    this.page = new IdentifySourcePage(this.w);
  }

  @given ('the Identify a Source screen is displayed')
  public async displayIdentifySrcScreen () {
    await this.base.displayIdentifySrcScreen ();
  }
```

the challenge now was that the page objects need this reference

3. add world object to the page constructor

```
  constructor (world: SeleniumWorld) {
    this.w = world;
   // this.driver = world.driver;   don't do this!!!!
  }
```
do not get a refernce to driver - it isn't populated yet and will change for each scenario!!!!

4. finally, initialize the driver in  a @before hook

```
  @before()
  public async before () {
    this.w.driver = await new SeleniumWebdriver.Builder ()
      .forBrowser ('chrome')
      .build ();
  }
```

5. and close it in an @after hook

```
  @after ()
  public closeAfter (scenarioResult: any) {
    this.w.driver.close();
  }
```

this ensures that the driver gets reinitialized for each scenario

**Comment by kferrone** [comment]
I have discovered where the WorldObject goes. 

Simply:
```ts
this._worldObj
```

**Comment by thees** [comment]
Type support would be nice. Otherwise you cannot access this with typescript except marking it with //ts-ignore

**Comment by timjroberts** [comment]
As the above mentioned ticket eludes, tsflow is adapting CucumberJS to make it more object-oriented. The idea is that the class itself becomes your world (since `this` would represent a reference to the instance of your class). It was all originally conceived as an experiment with TypeScript decorators, but CucumberJS has moved on since then - this repo hasn't. Perhaps it's time for a refresh.

**Comment by jthomerson** [comment]
Yes, the state class makes a lot of sense in the context of cucumber-tsflow, and works really well. The one missing piece is that with the Cucumber CLI, you can supply `--world-parameters`, a JSON object, and those are fed into the world. This really helps with things like building on multiple environments, so you can pass in dynamic configuration to your test suite.

If the tsflow state objects could take those parameters as an optional argument to their constructor, I think that would be really helpful.

**Comment by JSLadeo** [comment]
Hello, I got the same problem: cant attach a screenshot to multiple-cucumber-html-reporter with typescrypt. 
I try use "this._worldObj" but not working too.
My version :
. Node : 16.15.1
. "cucumber-tsflow": "^4.0.0-preview.7"
. "typescript": "^4.7.4"

`private _worldObj: any;
@after()
public async after(scenario: any, callback: any){
await this.driver.takeScreenshot().then((stream) => {
                    this._worldObj.attach(stream, 'image/png');
                    fs.writeFileSync('error.html', `<img src="data:image/png;base64,${stream}"/>`);
                    //callback();
                })
}`
I try lot of thing but in this case i replace "scenario" by "this._worldObj" after i declare it as private to attach fonction.
Here i got error: "Cannot attach when a step/hook is not running. Ensure your step/hook waits for the attach to finish"
If someone know a simple way to configure  attach screenshot to a scenario, or tell me how to go ahead of this problem . Would be awesome. Thanks
