### ISSUE TITLE
Step retry support?

### ISSUE THREAD

**Issue by degerlac** [timjroberts/cucumber-js-tsflow#42]
Is there a way to utilize the retries with this library?
Trying to migrate
Given(/^Some state$/,  { wrapperOptions: { retry: 4 } }, () => {

}

**Comment by mikehaas763** [comment]
From a quick look at the decorator code, I don't think it's possible as is. Ideally, the decorators would just be a pass-through that supports all API options that the underlying cucumber lib supports

**Comment by Fryuni** [comment]
We now expose the `wrapperOptions` in the step decorators. Keep in mind that the this API is marked as deprecated on Cucumber itself an may be removed from Cucumber at any moment.

I'll try to keep compatibility with Cucumber 7 for as long as I can :)
