### ISSUE TITLE
Location property set wrong

### ISSUE THREAD

**Issue by MSafter** [timjroberts/cucumber-js-tsflow#44]
Hi, 

the cumulus result json has the cumulus-tsflow node_modules path and not the test paths.

![image](https://user-images.githubusercontent.com/5517637/78338554-4a92d300-7593-11ea-94d6-c454ae313737.png)

**Comment by Fryuni** [comment]
Cucumber has no official support for specifying that a particular stack frame is a helper and should be ignored in when looking for the step definition location.

I added a hacky workaround for Cucumber 8 in 9c2e33259fd2e781c422129ce0f440976a083cea

I'll gladly add a proper implementation for this if Cucumber adds support for it.
