### ISSUE TITLE
Cannot reference some tag expression properly

### ISSUE THREAD

**Issue by wudong** [timjroberts/cucumber-js-tsflow#45]
The code below add a '@' before the tag value if there is no '@'. 
This prevents the usage of some tag expression such as 'not @tagName', cause it will generate a tag expression that cannot be parsed. 

Is it reasonable to remove this behavior and leave all the tag processing to cucumber-js ? 

https://github.com/timjroberts/cucumber-js-tsflow/blob/e71d897a72eccf27f2ccf322e233d080dbaf9a0c/cucumber-tsflow/src/hook-decorators.ts#L29

**Comment by mikehaas763** [comment]
It makes sense to me to leave all processing to cucumber-js, this lib should mainly be about providing a new interface or facade to the underlying cucumber-js. That said, I'm not sure why this `@` prefix was added in the first place.

**Comment by kferrone** [comment]
I just noticed that too. I was already planning to just remove for our org, I'll make a PR for this too.
