### ISSUE TITLE
Vote for IntelliJ and WebStorm support for Cucumber TSFlow

### ISSUE THREAD

**Issue by jan-molak** [timjroberts/cucumber-js-tsflow#5]
Hi Tim and many thanks for your excellent work on Cucumber TSFlow 👍 

Just wanted to let you know that I've asked @avokin, author of the [CucumberJS IntelliJ plugin](https://plugins.jetbrains.com/plugin/7418?pr=) to consider adding support for Cucumber TSFlow to [IntelliJ](https://www.jetbrains.com/idea/).

Andrey has [created a ticket](https://youtrack.jetbrains.com/issue/WEB-22516) which I've already voted on, so perhaps yourself and our fellow devs who stumble upon this post would like to do the same? 😄 

I've also [tweeted about it](https://twitter.com/JanMolak/status/756461587507142656), so feel free to RT if you'd like to help make this happen!

All the best,
Jan

**Comment by tommysullivan** [comment]
voted for it!

**Comment by mica16** [comment]
Would be great! 
Is there some news about that?

**Comment by mickaelw** [comment]
+1
