### ISSUE TITLE
Missing code content on version 3.2.1 

### ISSUE THREAD

**Issue by workfel** [timjroberts/cucumber-js-tsflow#59]
Hello,
I have juste downloaded the last version `3.2.1` with `npm` and there is nothing on it. 
There are just : 

- package.json
- README.md

I think there was error during the `npm publish` 

Thx

**Comment by timjroberts** [comment]
Thanks @workfel - I've just pushed `3.2.2` which will hopefully fix it.

**Comment by workfel** [comment]
@timjroberts thanks it's working now.

**Comment by workfel** [comment]
@timjroberts  Thanks it's working now
