### ISSUE TITLE
Replace binding decorator with more meaningful name

### ISSUE THREAD

**Issue by codeandcats** [timjroberts/cucumber-js-tsflow#7]
`@binding` decorator is great, but a little vague and generic in its name, compared to `given`, `when`, `then`, etc.

Suggest reexporting it as something more meaningful and domain specific like `feature` or `spec`.

**Comment by codeandcats** [comment]
Ah, I just realised this is to match SpecFlow's `binding` attribute.

**Comment by timjroberts** [comment]
Yeah, the decorators are all based on SpecFlow's attributes.
