### ISSUE TITLE
Support for upcoming Cucumber 7.x

### ISSUE THREAD

**Issue by x80486** [timjroberts/cucumber-js-tsflow#71]
## Is your feature request related to a problem?

I was trying the upcoming Cucumber 7.x (now "located at" `@cucumber/cucumber`) and `cucumber-js-tsflow` was looking for the previous version.

## Describe the solution you'd like

To work towards the newer version.

**Comment by wudong** [comment]
@x80486 code is merged now on master but will wait for the official 7.0.0 to be released.

**Comment by timjroberts** [comment]
I have published a `4.0.0-preview.4` which will now import the correct version of `@cucumber/cucumber`.
