### ISSUE TITLE
Step-Specific Timeout

### ISSUE THREAD

**Issue by OhadR** [timjroberts/cucumber-js-tsflow#72]
Hi,

maybe I miss something, but does this (great) package supports timeouts in a **step level**? I use the code below to set the "global" timeout, i.e. for ALL steps:

```
var {setDefaultTimeout} = require('cucumber');
setDefaultTimeout(10 * 1000); 

```
So far so good, but now I have a single step which take a lot of time so I want to allow _specifically_ only this step to run 5 minutes without getting timeout error. 

How can I achieve that?

currently I see no choice but to use "plain" cucumber again:
```

import { When } from "cucumber";

function sleep(seconds) {
    return new Promise(resolve => setTimeout(resolve, seconds * 1000));
}

When('wait {int} minutes', {timeout: 60 * 1000}, async function(numMinutes: number) {
    await sleep(numMinutes * 60);
});
```
is there a more elegant way, using tsflow?

(related to #29 )

**Comment by wudong** [comment]
Hi OhadR, 
the step specific timeout can actually be set now, for when/then/given, but not for the before/after hookd. 
```
@given(/^some step to be executed$/, undefined, 1000) 
public someGiven(){
}
```
here, we set the timeout to be 1000ms.
note the ```undefined``` before the timeout argument; it is for tag.

can you verify this works for u? if not i have have further check.

**Comment by wudong** [comment]
Added support for timeout in before/after hooks now.

**Comment by OhadR** [comment]
superb! thanks @wudong

**Comment by OhadR** [comment]
superb! thanks @wudong

tried to check it now. Can I parametrize the '1000' value? meaning, can I write something like:

```
@given(/^some step to be executed$/, undefined, someParamFromStep) 
public someGiven(param: number){
}
```

**Comment by OhadR** [comment]
superb! thanks @wudong

tried to check it now. working perfectly.

I would add it also to the docs :-)

**Comment by lagartoLomo** [comment]
How can I add a 'timeout' to the 'before/after hooks'?

Can you give me an example, the documentation does not provide one. Thank you.

Do I need a specific version ?
