### ISSUE TITLE
beforeAll / afterAll

### ISSUE THREAD

**Issue by OhadR** [timjroberts/cucumber-js-tsflow#78]
cucumber supports [BeforeAll and AfterAll](https://github.com/cucumber/cucumber-js/blob/master/docs/support_files/hooks.md#beforeall--afterall)

Is there a way to support that via cucumber-js-tsflow?

thanks!

**Comment by garfieldnate** [comment]
There is a fork here with these hooks implemented: https://github.com/wudong/cucumber-js-tsflow/tree/before_after_all_hooks. It has a release to NPM, too. Not sure why this wasn't just sent as a PR to this repo.
