### ISSUE TITLE
Cannot use import statement outside a module

### ISSUE THREAD

**Issue by Retanaar** [timjroberts/cucumber-js-tsflow#79]
Hi,
I received error message while trying to run tests

import React from 'react';
^^^^^^

SyntaxError: Cannot use import statement outside a module

my cucumber.js profile

const common = [
  'src/**/specs/**/*.feature', 
  '--require-module ts-node/register', 
  '--require-module jsdom-global/register',
  '--require src/**/specs/step-definitions/**/*.steps.{ts,tsx}', 
  '--format progress-bar' 
].join(' ');

module.exports = {
  default: common
};

runing tests with ./node_modules/.bin/cucumber-js -p default

**Comment by moshebeeri** [comment]
I have the same issue with react-typescript project, any resolution?

**Comment by Fryuni** [comment]
Sorry to come to this after almost 2 years, but I don't do frontend dev nearly at all, so I don't know what libraries are even involved in reproducing this.

Could one of you, if you are still facing this issue, provide a minimal reproduction repo?
A single hello-world component with a test that always passes should suffice.

> Btw. the tsconfig.json is the same our app uses to start. So I would prefer not to change it.

As a side note, you can add a tsconfig.json file inside your `step_definitions` folder, extending the definition from your app and modifying what you want to be different. The ts-node module will use the correct file.

```json
{
  "extends": "../tsconfig.json",
  "compilerOptions": {
    "module": "commonjs"
  }
}
```

It should not be necessary, but I thought it was nice to share 😄
