### ISSUE TITLE
Method decorators cause compiler error

### ISSUE THREAD

**Issue by codeandcats** [timjroberts/cucumber-js-tsflow#8]
When trying to compile steps with method bindings (`@given`, `@when`, `@then`, etc) I get the following error:

```
features/step_definitions/calculatorAdd.ts(16,5): error TS1241: Unable to resolve signature of method decorator when called as an expression.
Supplied parameters do not match any signature of call target.
```

This is demonstrated in this [bare-bones example](https://github.com/codeandcats/cucumber-js-tsflow-demo). Note that although the TypeScript compiler complains, the generated js works as expected.

**Comment by codeandcats** [comment]
Ping @timjroberts

**Comment by timjroberts** [comment]
The `target` compiler option is required in the `tsconfig.json` files.

If I change the tsconfig.json file in your features\step_definitions folder to include one:
```javascript
{
    "compilerOptions": {
        "experimentalDecorators": true,
        "module": "commonjs",
        "target": "es5"
    }
}
```

Then everything compiles as expected.

I've created a [pull request](https://github.com/codeandcats/cucumber-js-tsflow-demo/pull/1) for you to take a look at.
