### ISSUE TITLE
@before with tag is not working properly with cucumberjs > 0.9.5

### ISSUE THREAD

**Issue by alexwizp** [timjroberts/cucumber-js-tsflow#9]
For more details see 
https://github.com/cucumber/cucumber-js/blob/master/CHANGELOG.md

Section: 
updated tagged hook interface (Charlie Rudolph)

how to update:

this.Before('@tagA', function() { ... })
// becomes
this.Before({tags: ['@tagA']}, function() { ... })

this.Before('@tagA', '@tagB,@tagC', function() { ... })
// becomes
this.Before({tags: ['@tagA', '@tagB,@tagC']}, function() { ... })

**Comment by alexwizp** [comment]
Also it will be great if you add ability to set timeout for Hooks(@before and @after)

**Comment by TAGC** [comment]
WHO DISTURBS MY SLUMBER

**Comment by alexwizp** [comment]
@timjroberts Do you have any updates?

**Comment by timjroberts** [comment]
Will try and take a look as soon as I can. Family commitments are occupying my evenings at the moment.

**Comment by AlexandrosD** [comment]
For now a downgrade to cucumber v0.9.5 does the trick, but we miss the
other goodies..

2016-08-22 17:51 GMT+03:00 Tim Roberts <notifications@github.com>:

**Comment by timjroberts** [comment]
Hopefully this will now be fixed in v1.2.0. Let me know how it goes!

**Comment by AlexandrosD** [comment]
I can confirm that it works as expected, at least with one tag passed to the `@before()` or `@after()`
